#
# Makefile [approx]
#
# Copyright © 2012 Hanspeter Winkler
#

#
# definitions
#

include ../Makedefs

LIBMAJOR = 2

LIBMINOR = 1.0

PRFX = approx

DIRS = config neldermead

EXTRADIRS = 

SOLIBS = -L../lib -l$(LIBPRFX)core


#
# dependencies
#

neldermead: config


#
# common rules
#

include ../make/Makecommon
