/*
 * FILE : sfftw_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header: /ami/sw/cvsroot/pyleginon/fftw-numpy/sfftw_wrap.c,v 1.2 2004-02-10 20:39:52 pulokas Exp $
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log: not supported by cvs2svn $
 * Revision 1.1.2.1  2004/01/28 21:11:34  pulokas
 * added directory for fftw stuff
 *
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header: /ami/sw/cvsroot/pyleginon/fftw-numpy/sfftw_wrap.c,v 1.2 2004-02-10 20:39:52 pulokas Exp $
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initsfftw

#define SWIG_name    "sfftw"

#include "sfftw.h"      /* This one has fftw_real = real */
#include "srfftw.h"
#include "Python.h"
#include "Numeric/arrayobject.h"
extern fftw_plan fftw_create_plan_specific(int ,fftw_direction ,int ,fftw_complex *,int ,fftw_complex *,int );
extern fftw_plan fftw_create_plan(int ,fftw_direction ,int );
extern void fftw_print_plan(fftw_plan );
extern void fftw_destroy_plan(fftw_plan );
extern void fftw(fftw_plan ,int ,fftw_complex *,int ,int ,fftw_complex *,int ,int );
extern void fftw_one(fftw_plan ,fftw_complex *,fftw_complex *);
extern void fftw_die(const char *);
extern void fftw_check_memory_leaks();
extern void fftw_print_max_memory_usage();
extern size_t fftw_sizeof_fftw_real();
extern void fftw_forget_wisdom();
extern void fftw_export_wisdom_to_file(FILE *);
extern fftw_status fftw_import_wisdom_from_file(FILE *);
extern char *fftw_export_wisdom_to_string();
extern fftw_status fftw_import_wisdom_from_string(const char *);
extern void fftw_fprint_plan(FILE *,fftw_plan );
extern fftwnd_plan fftw2d_create_plan(int ,int ,fftw_direction ,int );
extern fftwnd_plan fftw3d_create_plan(int ,int ,int ,fftw_direction ,int );
extern fftwnd_plan fftwnd_create_plan(int ,const int *,fftw_direction ,int );
extern fftwnd_plan fftw2d_create_plan_specific(int ,int ,fftw_direction ,int ,fftw_complex *,int ,fftw_complex *,int );
extern fftwnd_plan fftw3d_create_plan_specific(int ,int ,int ,fftw_direction ,int ,fftw_complex *,int ,fftw_complex *,int );
extern fftwnd_plan fftwnd_create_plan_specific(int ,const int *,fftw_direction ,int ,fftw_complex *,int ,fftw_complex *,int );
extern void fftwnd_destroy_plan(fftwnd_plan );
extern void fftwnd_fprint_plan(FILE *,fftwnd_plan );
extern void fftwnd_print_plan(fftwnd_plan );
extern void fftwnd(fftwnd_plan ,int ,fftw_complex *,int ,int ,fftw_complex *,int ,int );
extern void fftwnd_one(fftwnd_plan ,fftw_complex *,fftw_complex *);
extern void rfftw(rfftw_plan ,int ,fftw_real *,int ,int ,fftw_real *,int ,int );
extern void rfftw_one(rfftw_plan ,fftw_real *,fftw_real *);
extern rfftw_plan rfftw_create_plan_specific(int ,fftw_direction ,int ,fftw_real *,int ,fftw_real *,int );
extern rfftw_plan rfftw_create_plan(int ,fftw_direction ,int );
extern void rfftw_destroy_plan(rfftw_plan );
extern void rfftw_fprint_plan(FILE *,rfftw_plan );
extern void rfftw_print_plan(rfftw_plan );
extern void rfftw_executor_simple(int ,fftw_real *,fftw_real *,fftw_plan_node *,int ,int ,fftw_recurse_kind );
extern rfftwnd_plan rfftwnd_create_plan_specific(int ,const int *,fftw_direction ,int ,fftw_real *,int ,fftw_real *,int );
extern rfftwnd_plan rfftw2d_create_plan_specific(int ,int ,fftw_direction ,int ,fftw_real *,int ,fftw_real *,int );
extern rfftwnd_plan rfftw3d_create_plan_specific(int ,int ,int ,fftw_direction ,int ,fftw_real *,int ,fftw_real *,int );
extern rfftwnd_plan rfftwnd_create_plan(int ,const int *,fftw_direction ,int );
extern rfftwnd_plan rfftw2d_create_plan(int ,int ,fftw_direction ,int );
extern rfftwnd_plan rfftw3d_create_plan(int ,int ,int ,fftw_direction ,int );
extern void rfftwnd_destroy_plan(rfftwnd_plan );
extern void rfftwnd_fprint_plan(FILE *,rfftwnd_plan );
extern void rfftwnd_print_plan(rfftwnd_plan );
extern void rfftwnd_real_to_complex(rfftwnd_plan ,int ,fftw_real *,int ,int ,fftw_complex *,int ,int );
extern void rfftwnd_complex_to_real(rfftwnd_plan ,int ,fftw_complex *,int ,int ,fftw_real *,int ,int );
extern void rfftwnd_one_real_to_complex(rfftwnd_plan ,fftw_real *,fftw_complex *);
extern void rfftwnd_one_complex_to_real(rfftwnd_plan ,fftw_complex *,fftw_real *);
static PyObject *_wrap_fftw_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _result;
    int  _arg0;
    fftw_direction  _arg1;
    int  _arg2;
    fftw_complex * _arg3;
    int  _arg4;
    fftw_complex * _arg5;
    int  _arg6;
    PyObject * _obj3 = 0;
    PyObject * _obj5 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiOiOi:fftw_create_plan_specific",&_arg0,&_arg1,&_arg2,&_obj3,&_arg4,&_obj5,&_arg6)) 
        return NULL;
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj3, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg3 = (fftw_complex *)arr->data;
  _obj3 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_complex *)arr->data;
  _obj5 = (PyObject *)arr;
}
    _result = (fftw_plan *) malloc(sizeof(fftw_plan ));
    *(_result) = fftw_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftw_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj3); 
}
{
  Py_XDECREF(_obj5); 
}
    return _resultobj;
}

static PyObject *_wrap_fftw_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _result;
    int  _arg0;
    fftw_direction  _arg1;
    int  _arg2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iii:fftw_create_plan",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (fftw_plan *) malloc(sizeof(fftw_plan ));
    *(_result) = fftw_create_plan(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftw_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fftw_print_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftw_print_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftw_print_plan. Expected _fftw_plan_p.");
        return NULL;
        }
    }
    fftw_print_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_destroy_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftw_destroy_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftw_destroy_plan. Expected _fftw_plan_p.");
        return NULL;
        }
    }
    fftw_destroy_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _arg0;
    int  _arg1;
    fftw_complex * _arg2;
    int  _arg3;
    int  _arg4;
    fftw_complex * _arg5;
    int  _arg6;
    int  _arg7;
    char * _argc0 = 0;
    PyObject * _obj2 = 0;
    PyObject * _obj5 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siOiiOii:fftw",&_argc0,&_arg1,&_obj2,&_arg3,&_arg4,&_obj5,&_arg6,&_arg7)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftw. Expected _fftw_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_complex *)arr->data;
  _obj5 = (PyObject *)arr;
}
    fftw(*_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj2); 
}
{
  Py_XDECREF(_obj5); 
}
    return _resultobj;
}

static PyObject *_wrap_fftw_one(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_plan * _arg0;
    fftw_complex * _arg1;
    fftw_complex * _arg2;
    char * _argc0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sOO:fftw_one",&_argc0,&_obj1,&_obj2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftw_one. Expected _fftw_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_complex *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
    fftw_one(*_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1); 
}
{
  Py_XDECREF(_obj2); 
}
    return _resultobj;
}

static PyObject *_wrap_fftw_die(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftw_die",&_arg0)) 
        return NULL;
    fftw_die(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_check_memory_leaks(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":fftw_check_memory_leaks")) 
        return NULL;
    fftw_check_memory_leaks();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_print_max_memory_usage(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":fftw_print_max_memory_usage")) 
        return NULL;
    fftw_print_max_memory_usage();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_sizeof_fftw_real(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    size_t * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":fftw_sizeof_fftw_real")) 
        return NULL;
    _result = (size_t *) malloc(sizeof(size_t ));
    *(_result) = fftw_sizeof_fftw_real();
    SWIG_MakePtr(_ptemp, (void *) _result,"_size_t_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fftw_forget_wisdom(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":fftw_forget_wisdom")) 
        return NULL;
    fftw_forget_wisdom();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_export_wisdom_to_file(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _arg0;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:fftw_export_wisdom_to_file",&_obj0)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    fftw_export_wisdom_to_file(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw_import_wisdom_from_file(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_status  _result;
    FILE * _arg0;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:fftw_import_wisdom_from_file",&_obj0)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    _result = (fftw_status )fftw_import_wisdom_from_file(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fftw_export_wisdom_to_string(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;

    self = self;
    if(!PyArg_ParseTuple(args,":fftw_export_wisdom_to_string")) 
        return NULL;
    _result = (char *)fftw_export_wisdom_to_string();
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_fftw_import_wisdom_from_string(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftw_status  _result;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftw_import_wisdom_from_string",&_arg0)) 
        return NULL;
    _result = (fftw_status )fftw_import_wisdom_from_string(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fftw_fprint_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _arg0;
    fftw_plan * _arg1;
    PyObject * _obj0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:fftw_fprint_plan",&_obj0,&_argc1)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_fftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fftw_fprint_plan. Expected _fftw_plan_p.");
        return NULL;
        }
    }
    fftw_fprint_plan(_arg0,*_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftw2d_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiii:fftw2d_create_plan",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftw2d_create_plan(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fftw3d_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    fftw_direction  _arg3;
    int  _arg4;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiii:fftw3d_create_plan",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftw3d_create_plan(_arg0,_arg1,_arg2,_arg3,_arg4);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fftwnd_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int * _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    PyObject * _obj1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iOii:fftwnd_create_plan",&_arg0,&_obj1,&_arg2,&_arg3)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is integer */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_INT, 1, 1)) == NULL) return NULL;
  _arg1 = (int *)arr->data;
  _obj1 = (PyObject *)arr;
}
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftwnd_create_plan(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj1);
}
    return _resultobj;
}

static PyObject *_wrap_fftw2d_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    fftw_complex * _arg4;
    int  _arg5;
    fftw_complex * _arg6;
    int  _arg7;
    PyObject * _obj4 = 0;
    PyObject * _obj6 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiiOiOi:fftw2d_create_plan_specific",&_arg0,&_arg1,&_arg2,&_arg3,&_obj4,&_arg5,&_obj6,&_arg7)) 
        return NULL;
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj4, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg4 = (fftw_complex *)arr->data;
  _obj4 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj6, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg6 = (fftw_complex *)arr->data;
  _obj6 = (PyObject *)arr;
}
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftw2d_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj4); 
}
{
  Py_XDECREF(_obj6); 
}
    return _resultobj;
}

static PyObject *_wrap_fftw3d_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    fftw_direction  _arg3;
    int  _arg4;
    fftw_complex * _arg5;
    int  _arg6;
    fftw_complex * _arg7;
    int  _arg8;
    PyObject * _obj5 = 0;
    PyObject * _obj7 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiiiOiOi:fftw3d_create_plan_specific",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4,&_obj5,&_arg6,&_obj7,&_arg8)) 
        return NULL;
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_complex *)arr->data;
  _obj5 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj7, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg7 = (fftw_complex *)arr->data;
  _obj7 = (PyObject *)arr;
}
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftw3d_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj5); 
}
{
  Py_XDECREF(_obj7); 
}
    return _resultobj;
}

static PyObject *_wrap_fftwnd_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _result;
    int  _arg0;
    int * _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    fftw_complex * _arg4;
    int  _arg5;
    fftw_complex * _arg6;
    int  _arg7;
    PyObject * _obj1 = 0;
    PyObject * _obj4 = 0;
    PyObject * _obj6 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iOiiOiOi:fftwnd_create_plan_specific",&_arg0,&_obj1,&_arg2,&_arg3,&_obj4,&_arg5,&_obj6,&_arg7)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is integer */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_INT, 1, 1)) == NULL) return NULL;
  _arg1 = (int *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj4, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg4 = (fftw_complex *)arr->data;
  _obj4 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj6, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg6 = (fftw_complex *)arr->data;
  _obj6 = (PyObject *)arr;
}
    _result = (fftwnd_plan *) malloc(sizeof(fftwnd_plan ));
    *(_result) = fftwnd_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    SWIG_MakePtr(_ptemp, (void *) _result,"_fftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj1);
}
{
  Py_XDECREF(_obj4); 
}
{
  Py_XDECREF(_obj6); 
}
    return _resultobj;
}

static PyObject *_wrap_fftwnd_destroy_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftwnd_destroy_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftwnd_destroy_plan. Expected _fftwnd_plan_p.");
        return NULL;
        }
    }
    fftwnd_destroy_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftwnd_fprint_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _arg0;
    fftwnd_plan * _arg1;
    PyObject * _obj0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:fftwnd_fprint_plan",&_obj0,&_argc1)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_fftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fftwnd_fprint_plan. Expected _fftwnd_plan_p.");
        return NULL;
        }
    }
    fftwnd_fprint_plan(_arg0,*_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftwnd_print_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:fftwnd_print_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftwnd_print_plan. Expected _fftwnd_plan_p.");
        return NULL;
        }
    }
    fftwnd_print_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fftwnd(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _arg0;
    int  _arg1;
    fftw_complex * _arg2;
    int  _arg3;
    int  _arg4;
    fftw_complex * _arg5;
    int  _arg6;
    int  _arg7;
    char * _argc0 = 0;
    PyObject * _obj2 = 0;
    PyObject * _obj5 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siOiiOii:fftwnd",&_argc0,&_arg1,&_obj2,&_arg3,&_arg4,&_obj5,&_arg6,&_arg7)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftwnd. Expected _fftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_complex *)arr->data;
  _obj5 = (PyObject *)arr;
}
    fftwnd(*_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj2); 
}
{
  Py_XDECREF(_obj5); 
}
    return _resultobj;
}

static PyObject *_wrap_fftwnd_one(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    fftwnd_plan * _arg0;
    fftw_complex * _arg1;
    fftw_complex * _arg2;
    char * _argc0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sOO:fftwnd_one",&_argc0,&_obj1,&_obj2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_fftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fftwnd_one. Expected _fftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_complex *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
    fftwnd_one(*_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1); 
}
{
  Py_XDECREF(_obj2); 
}
    return _resultobj;
}

static PyObject *_wrap_rfftw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _arg0;
    int  _arg1;
    fftw_real * _arg2;
    int  _arg3;
    int  _arg4;
    fftw_real * _arg5;
    int  _arg6;
    int  _arg7;
    char * _argc0 = 0;
    PyObject * _obj2 = 0;
    PyObject * _obj5 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siOiiOii:rfftw",&_argc0,&_arg1,&_obj2,&_arg3,&_arg4,&_obj5,&_arg6,&_arg7)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftw. Expected _rfftw_plan_p.");
        return NULL;
        }
    }
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_real *)arr->data;
  _obj2 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_real *)arr->data;
  _obj5 = (PyObject *)arr;
}
    rfftw(*_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj2);
}
{
  Py_XDECREF(_obj5);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw_one(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _arg0;
    fftw_real * _arg1;
    fftw_real * _arg2;
    char * _argc0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sOO:rfftw_one",&_argc0,&_obj1,&_obj2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftw_one. Expected _rfftw_plan_p.");
        return NULL;
        }
    }
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_real *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_real *)arr->data;
  _obj2 = (PyObject *)arr;
}
    rfftw_one(*_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1);
}
{
  Py_XDECREF(_obj2);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _result;
    int  _arg0;
    fftw_direction  _arg1;
    int  _arg2;
    fftw_real * _arg3;
    int  _arg4;
    fftw_real * _arg5;
    int  _arg6;
    PyObject * _obj3 = 0;
    PyObject * _obj5 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiOiOi:rfftw_create_plan_specific",&_arg0,&_arg1,&_arg2,&_obj3,&_arg4,&_obj5,&_arg6)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj3, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg3 = (fftw_real *)arr->data;
  _obj3 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_real *)arr->data;
  _obj5 = (PyObject *)arr;
}
    _result = (rfftw_plan *) malloc(sizeof(rfftw_plan ));
    *(_result) = rfftw_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftw_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj3);
}
{
  Py_XDECREF(_obj5);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _result;
    int  _arg0;
    fftw_direction  _arg1;
    int  _arg2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iii:rfftw_create_plan",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (rfftw_plan *) malloc(sizeof(rfftw_plan ));
    *(_result) = rfftw_create_plan(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftw_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_rfftw_destroy_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:rfftw_destroy_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftw_destroy_plan. Expected _rfftw_plan_p.");
        return NULL;
        }
    }
    rfftw_destroy_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftw_fprint_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _arg0;
    rfftw_plan * _arg1;
    PyObject * _obj0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:rfftw_fprint_plan",&_obj0,&_argc1)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_rfftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of rfftw_fprint_plan. Expected _rfftw_plan_p.");
        return NULL;
        }
    }
    rfftw_fprint_plan(_arg0,*_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftw_print_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftw_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:rfftw_print_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftw_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftw_print_plan. Expected _rfftw_plan_p.");
        return NULL;
        }
    }
    rfftw_print_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftw_executor_simple(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;
    fftw_real * _arg1;
    fftw_real * _arg2;
    fftw_plan_node * _arg3;
    int  _arg4;
    int  _arg5;
    fftw_recurse_kind  _arg6;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;
    char * _argc3 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"iOOsiii:rfftw_executor_simple",&_arg0,&_obj1,&_obj2,&_argc3,&_arg4,&_arg5,&_arg6)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_real *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_real *)arr->data;
  _obj2 = (PyObject *)arr;
}
    if (_argc3) {
        if (SWIG_GetPtr(_argc3,(void **) &_arg3,"_fftw_plan_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 4 of rfftw_executor_simple. Expected _fftw_plan_node_p.");
        return NULL;
        }
    }
    rfftw_executor_simple(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1);
}
{
  Py_XDECREF(_obj2);
}
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int * _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    fftw_real * _arg4;
    int  _arg5;
    fftw_real * _arg6;
    int  _arg7;
    PyObject * _obj1 = 0;
    PyObject * _obj4 = 0;
    PyObject * _obj6 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iOiiOiOi:rfftwnd_create_plan_specific",&_arg0,&_obj1,&_arg2,&_arg3,&_obj4,&_arg5,&_obj6,&_arg7)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is integer */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_INT, 1, 1)) == NULL) return NULL;
  _arg1 = (int *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj4, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg4 = (fftw_real *)arr->data;
  _obj4 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj6, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg6 = (fftw_real *)arr->data;
  _obj6 = (PyObject *)arr;
}
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftwnd_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj1);
}
{
  Py_XDECREF(_obj4);
}
{
  Py_XDECREF(_obj6);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw2d_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    fftw_real * _arg4;
    int  _arg5;
    fftw_real * _arg6;
    int  _arg7;
    PyObject * _obj4 = 0;
    PyObject * _obj6 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiiOiOi:rfftw2d_create_plan_specific",&_arg0,&_arg1,&_arg2,&_arg3,&_obj4,&_arg5,&_obj6,&_arg7)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj4, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg4 = (fftw_real *)arr->data;
  _obj4 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj6, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg6 = (fftw_real *)arr->data;
  _obj6 = (PyObject *)arr;
}
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftw2d_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj4);
}
{
  Py_XDECREF(_obj6);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw3d_create_plan_specific(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    fftw_direction  _arg3;
    int  _arg4;
    fftw_real * _arg5;
    int  _arg6;
    fftw_real * _arg7;
    int  _arg8;
    PyObject * _obj5 = 0;
    PyObject * _obj7 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiiiOiOi:rfftw3d_create_plan_specific",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4,&_obj5,&_arg6,&_obj7,&_arg8)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_real *)arr->data;
  _obj5 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj7, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg7 = (fftw_real *)arr->data;
  _obj7 = (PyObject *)arr;
}
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftw3d_create_plan_specific(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj5);
}
{
  Py_XDECREF(_obj7);
}
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int * _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    PyObject * _obj1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iOii:rfftwnd_create_plan",&_arg0,&_obj1,&_arg2,&_arg3)) 
        return NULL;
{
  /* Check to see if input is a NumPy array and if it is integer */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_INT, 1, 1)) == NULL) return NULL;
  _arg1 = (int *)arr->data;
  _obj1 = (PyObject *)arr;
}
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftwnd_create_plan(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  Py_XDECREF(_obj1);
}
    return _resultobj;
}

static PyObject *_wrap_rfftw2d_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    fftw_direction  _arg2;
    int  _arg3;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiii:rfftw2d_create_plan",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftw2d_create_plan(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_rfftw3d_create_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    fftw_direction  _arg3;
    int  _arg4;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiiii:rfftw3d_create_plan",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    _result = (rfftwnd_plan *) malloc(sizeof(rfftwnd_plan ));
    *(_result) = rfftw3d_create_plan(_arg0,_arg1,_arg2,_arg3,_arg4);
    SWIG_MakePtr(_ptemp, (void *) _result,"_rfftwnd_plan_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_destroy_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:rfftwnd_destroy_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_destroy_plan. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
    rfftwnd_destroy_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_fprint_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _arg0;
    rfftwnd_plan * _arg1;
    PyObject * _obj0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:rfftwnd_fprint_plan",&_obj0,&_argc1)) 
        return NULL;
{
  if (!(PyFile_Check(_obj0))) {
        PyErr_SetString(PyExc_TypeError, "Argument must be a File");
        return NULL;
  }
  _arg0 = PyFile_AsFile(_obj0);
}
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of rfftwnd_fprint_plan. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
    rfftwnd_fprint_plan(_arg0,*_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_print_plan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:rfftwnd_print_plan",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_print_plan. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
    rfftwnd_print_plan(*_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_real_to_complex(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    int  _arg1;
    fftw_real * _arg2;
    int  _arg3;
    int  _arg4;
    fftw_complex * _arg5;
    int  _arg6;
    int  _arg7;
    char * _argc0 = 0;
    PyObject * _obj2 = 0;
    PyObject * _obj5 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siOiiOii:rfftwnd_real_to_complex",&_argc0,&_arg1,&_obj2,&_arg3,&_arg4,&_obj5,&_arg6,&_arg7)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_real_to_complex. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_real *)arr->data;
  _obj2 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_complex *)arr->data;
  _obj5 = (PyObject *)arr;
}
    rfftwnd_real_to_complex(*_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj2);
}
{
  Py_XDECREF(_obj5); 
}
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_complex_to_real(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    int  _arg1;
    fftw_complex * _arg2;
    int  _arg3;
    int  _arg4;
    fftw_real * _arg5;
    int  _arg6;
    int  _arg7;
    char * _argc0 = 0;
    PyObject * _obj2 = 0;
    PyObject * _obj5 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siOiiOii:rfftwnd_complex_to_real",&_argc0,&_arg1,&_obj2,&_arg3,&_arg4,&_obj5,&_arg6,&_arg7)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_complex_to_real. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj5, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg5 = (fftw_real *)arr->data;
  _obj5 = (PyObject *)arr;
}
    rfftwnd_complex_to_real(*_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj2); 
}
{
  Py_XDECREF(_obj5);
}
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_one_real_to_complex(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    fftw_real * _arg1;
    fftw_complex * _arg2;
    char * _argc0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sOO:rfftwnd_one_real_to_complex",&_argc0,&_obj1,&_obj2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_one_real_to_complex. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_real *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_complex *)arr->data;
  _obj2 = (PyObject *)arr;
}
    rfftwnd_one_real_to_complex(*_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1);
}
{
  Py_XDECREF(_obj2); 
}
    return _resultobj;
}

static PyObject *_wrap_rfftwnd_one_complex_to_real(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    rfftwnd_plan * _arg0;
    fftw_complex * _arg1;
    fftw_real * _arg2;
    char * _argc0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sOO:rfftwnd_one_complex_to_real",&_argc0,&_obj1,&_obj2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_rfftwnd_plan_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of rfftwnd_one_complex_to_real. Expected _rfftwnd_plan_p.");
        return NULL;
        }
    }
{
  /* Make sure input is a NumPy array and a Complex Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj1, PyArray_CFLOAT, 0, 0)) == NULL) return NULL;
  _arg1 = (fftw_complex *)arr->data;
  _obj1 = (PyObject *)arr;
}
{
  /* Check to see if input is a NumPy array and if it is Float */
  PyArrayObject *arr;
  if ((arr = (PyArrayObject *) PyArray_ContiguousFromObject(_obj2, PyArray_FLOAT, 0, 0)) == NULL) return NULL;
  _arg2 = (fftw_real *)arr->data;
  _obj2 = (PyObject *)arr;
}
    rfftwnd_one_complex_to_real(*_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
{
  Py_XDECREF(_obj1); 
}
{
  Py_XDECREF(_obj2);
}
    return _resultobj;
}

static PyMethodDef sfftwMethods[] = {
	 { "rfftwnd_one_complex_to_real", _wrap_rfftwnd_one_complex_to_real, 1 },
	 { "rfftwnd_one_real_to_complex", _wrap_rfftwnd_one_real_to_complex, 1 },
	 { "rfftwnd_complex_to_real", _wrap_rfftwnd_complex_to_real, 1 },
	 { "rfftwnd_real_to_complex", _wrap_rfftwnd_real_to_complex, 1 },
	 { "rfftwnd_print_plan", _wrap_rfftwnd_print_plan, 1 },
	 { "rfftwnd_fprint_plan", _wrap_rfftwnd_fprint_plan, 1 },
	 { "rfftwnd_destroy_plan", _wrap_rfftwnd_destroy_plan, 1 },
	 { "rfftw3d_create_plan", _wrap_rfftw3d_create_plan, 1 },
	 { "rfftw2d_create_plan", _wrap_rfftw2d_create_plan, 1 },
	 { "rfftwnd_create_plan", _wrap_rfftwnd_create_plan, 1 },
	 { "rfftw3d_create_plan_specific", _wrap_rfftw3d_create_plan_specific, 1 },
	 { "rfftw2d_create_plan_specific", _wrap_rfftw2d_create_plan_specific, 1 },
	 { "rfftwnd_create_plan_specific", _wrap_rfftwnd_create_plan_specific, 1 },
	 { "rfftw_executor_simple", _wrap_rfftw_executor_simple, 1 },
	 { "rfftw_print_plan", _wrap_rfftw_print_plan, 1 },
	 { "rfftw_fprint_plan", _wrap_rfftw_fprint_plan, 1 },
	 { "rfftw_destroy_plan", _wrap_rfftw_destroy_plan, 1 },
	 { "rfftw_create_plan", _wrap_rfftw_create_plan, 1 },
	 { "rfftw_create_plan_specific", _wrap_rfftw_create_plan_specific, 1 },
	 { "rfftw_one", _wrap_rfftw_one, 1 },
	 { "rfftw", _wrap_rfftw, 1 },
	 { "fftwnd_one", _wrap_fftwnd_one, 1 },
	 { "fftwnd", _wrap_fftwnd, 1 },
	 { "fftwnd_print_plan", _wrap_fftwnd_print_plan, 1 },
	 { "fftwnd_fprint_plan", _wrap_fftwnd_fprint_plan, 1 },
	 { "fftwnd_destroy_plan", _wrap_fftwnd_destroy_plan, 1 },
	 { "fftwnd_create_plan_specific", _wrap_fftwnd_create_plan_specific, 1 },
	 { "fftw3d_create_plan_specific", _wrap_fftw3d_create_plan_specific, 1 },
	 { "fftw2d_create_plan_specific", _wrap_fftw2d_create_plan_specific, 1 },
	 { "fftwnd_create_plan", _wrap_fftwnd_create_plan, 1 },
	 { "fftw3d_create_plan", _wrap_fftw3d_create_plan, 1 },
	 { "fftw2d_create_plan", _wrap_fftw2d_create_plan, 1 },
	 { "fftw_fprint_plan", _wrap_fftw_fprint_plan, 1 },
	 { "fftw_import_wisdom_from_string", _wrap_fftw_import_wisdom_from_string, 1 },
	 { "fftw_export_wisdom_to_string", _wrap_fftw_export_wisdom_to_string, 1 },
	 { "fftw_import_wisdom_from_file", _wrap_fftw_import_wisdom_from_file, 1 },
	 { "fftw_export_wisdom_to_file", _wrap_fftw_export_wisdom_to_file, 1 },
	 { "fftw_forget_wisdom", _wrap_fftw_forget_wisdom, 1 },
	 { "fftw_sizeof_fftw_real", _wrap_fftw_sizeof_fftw_real, 1 },
	 { "fftw_print_max_memory_usage", _wrap_fftw_print_max_memory_usage, 1 },
	 { "fftw_check_memory_leaks", _wrap_fftw_check_memory_leaks, 1 },
	 { "fftw_die", _wrap_fftw_die, 1 },
	 { "fftw_one", _wrap_fftw_one, 1 },
	 { "fftw", _wrap_fftw, 1 },
	 { "fftw_destroy_plan", _wrap_fftw_destroy_plan, 1 },
	 { "fftw_print_plan", _wrap_fftw_print_plan, 1 },
	 { "fftw_create_plan", _wrap_fftw_create_plan, 1 },
	 { "fftw_create_plan_specific", _wrap_fftw_create_plan_specific, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initsfftw)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("sfftw", sfftwMethods);
	 d = PyModule_GetDict(m);

        import_array();
	 PyDict_SetItemString(d,"FFTW_FORWARD", PyInt_FromLong((long) FFTW_FORWARD));
	 PyDict_SetItemString(d,"FFTW_BACKWARD", PyInt_FromLong((long) FFTW_BACKWARD));
	 PyDict_SetItemString(d,"FFTW_SUCCESS", PyInt_FromLong((long) FFTW_SUCCESS));
	 PyDict_SetItemString(d,"FFTW_FAILURE", PyInt_FromLong((long) FFTW_FAILURE));
	 PyDict_SetItemString(d,"FFTW_NOTW", PyInt_FromLong((long) FFTW_NOTW));
	 PyDict_SetItemString(d,"FFTW_TWIDDLE", PyInt_FromLong((long) FFTW_TWIDDLE));
	 PyDict_SetItemString(d,"FFTW_GENERIC", PyInt_FromLong((long) FFTW_GENERIC));
	 PyDict_SetItemString(d,"FFTW_RADER", PyInt_FromLong((long) FFTW_RADER));
	 PyDict_SetItemString(d,"FFTW_REAL2HC", PyInt_FromLong((long) FFTW_REAL2HC));
	 PyDict_SetItemString(d,"FFTW_HC2REAL", PyInt_FromLong((long) FFTW_HC2REAL));
	 PyDict_SetItemString(d,"FFTW_HC2HC", PyInt_FromLong((long) FFTW_HC2HC));
	 PyDict_SetItemString(d,"FFTW_RGENERIC", PyInt_FromLong((long) FFTW_RGENERIC));
	 PyDict_SetItemString(d,"FFTW_NORMAL_RECURSE", PyInt_FromLong((long) FFTW_NORMAL_RECURSE));
	 PyDict_SetItemString(d,"FFTW_VECTOR_RECURSE", PyInt_FromLong((long) FFTW_VECTOR_RECURSE));
	 PyDict_SetItemString(d,"FFTW_ESTIMATE", PyInt_FromLong((long) (0)));
	 PyDict_SetItemString(d,"FFTW_MEASURE", PyInt_FromLong((long) (1)));
	 PyDict_SetItemString(d,"FFTW_OUT_OF_PLACE", PyInt_FromLong((long) (0)));
	 PyDict_SetItemString(d,"FFTW_IN_PLACE", PyInt_FromLong((long) (8)));
	 PyDict_SetItemString(d,"FFTW_USE_WISDOM", PyInt_FromLong((long) (16)));
	 PyDict_SetItemString(d,"FFTW_THREADSAFE", PyInt_FromLong((long) (128)));
	 PyDict_SetItemString(d,"FFTWND_FORCE_BUFFERED", PyInt_FromLong((long) (256)));
	 PyDict_SetItemString(d,"FFTW_NO_VECTOR_RECURSE", PyInt_FromLong((long) (512)));
	 PyDict_SetItemString(d,"FFTW_REAL_TO_COMPLEX", PyInt_FromLong((long) (FFTW_FORWARD)));
	 PyDict_SetItemString(d,"FFTW_COMPLEX_TO_REAL", PyInt_FromLong((long) (FFTW_BACKWARD)));
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
}
