#
# Makefile [fourier]
#
# Copyright © 2012 Hanspeter Winkler
#

#
# definitions
#

include   ../Makedefs

LIBMAJOR = 2

LIBMINOR = 1.0

PRFX = tomofourier

DIRS = config patch

EXTRADIRS = 

SOLIBS = -L../lib -l$(LIBPRFX)tomoseries



#
# dependencies
#

patch: config


#
# common rules
#

include ../make/Makecommon
