#
# Makefile [include]
#
# Copyright © 2012 Hanspeter Winkler
#


#
# definitions
#

include ../Makedefs


#
# make rules
#

.PHONY: help all install clean distclean depend

help:
	@ echo "usage: make [ all | install | depend | clean | distclean ]"

all:

install:

depend:

clean:

distclean:
	rm -f *.h

%.h: $(DIR)/%.h
	cp -p $< $@
