#
# Makefile [seriesmap]
#
# Copyright © 2012 Hanspeter Winkler
#

#
# definitions
#

include   ../Makedefs

LIBMAJOR = 2

LIBMINOR = 1.0

PRFX = tomoseriesmap

DIRS = config map

EXTRADIRS = 

SOLIBS = -L../lib -l$(LIBPRFX)tomoseries -l$(LIBPRFX)tomomap



#
# dependencies
#

map: config


#
# common rules
#

include ../make/Makecommon
