#
# Makefile [fourierop/config]
#
# Copyright © 2012 Hanspeter Winkler
#


#
# definitions
#

include   ../../Makedefs

PRFX = fourierop

INCS = $(PRFX)config.h $(PRFX)defs.h

OBJS = $(PRFX)config.o

CFLAGS = $(CLIBOPT)
CPPFLAGS = -I../../include $(CPPOPT)


#
# make rules
#

include ../../make/Makeconfig


#
# build dependencies
#

-include Makedeps
