export APPIONDIR="~/pyappion"
export PYTHONPATH="${PYTHONPATH}:${APPIONDIR}/lib"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPIONDIR}/lib"
export PATH="${PATH}:$APPIONDIR/particle_manager"
export FINDEMEXE="${APPIONDIR}/particle_manager/findem.exe"
