export TERMCOLOR='1;34'
if [ $UID == 0 ]
then
  PS1="\[\e[1;31m\]\u\[\e[0m\]@\[\e[${TERMCOLOR}m\]\h\[\e[0m\] \W] "
else
  PS1="\[\e[1;32m\]\u\[\e[0m\]@\[\e[${TERMCOLOR}m\]\h\[\e[0m\] \W] "
fi

umask 002

export APPIONPATH=/emg/sw/myami-3.1/appion

export PATH=/usr/bin:/bin:${APPIONPATH}/bin
#export PYTHONPATH=${APPIONPATH}/appionlib

export EDITOR=nano
export HISTSIZE=10000
export HISTFILESIZE=200000

alias dsort="du -sk * | sort -n | tail -50"


