#
# Makefile [fit]
#
# Copyright © 2012 Hanspeter Winkler
#

#
# definitions
#

include   ../Makedefs

LIBMAJOR = 2

LIBMINOR = 1.0

PRFX = tomofit

DIRS = config tiltfit

EXTRADIRS = 

SOLIBS = -L../lib -l$(LIBPRFX)tomo



#
# dependencies
#

fit: config


#
# common rules
#

include ../make/Makecommon
