#!/bin/bash
#
# COPYRIGHT:
#       The Leginon software is Copyright under
#       Apache License, Version 2.0
#       For terms of the license agreement
#       see  http://leginon.org
#
ps -ef | grep "launcher.py" | awk '{print$2}' | sort -n | xargs -t -iasdf kill -9 asdf

