
import os, socket

class LeginonObject(object):
	def __init__(self, newid=()):
		self.loc = {}
		self.loc['hostname'] = socket.gethostname()
		self.loc['pid'] = os.getpid()
		self.loc['pythonid'] = id(self)
		self.id = newid
		self.idcounter = 0

	def new_id(self):
		"""
		Returns a new unique ID in this LeginonObject system.
		The uniqueness of this ID assumes the following rule:
		Every LeginonObject (except the first) must be initialized 
		with an id that was generated by another LeginonObject using
		this method.
		"""
		newid = self.id + (self.idcounter,)
		self.idcounter += 1
		return newid

	def location(self):
		'return a dict describing the location of this object'
		return self.loc
