#!/usr/bin/env python

import sys
import time

inputfile = sys.argv[1]
f = open(inputfile)
lines = f.readlines()

seconds = int(lines[0][:-1])
fail = lines[1][:-1]

if fail == 'FAIL':
	raise RuntimeError('FAIL in params')

for i,line in enumerate(lines):
	line = line[:-1]
	print 'line %d says: %s' % (i, line)

t0 = time.time()
while True:
	print 'Time: ', time.time()
	time.sleep(5)
	if time.time() > t0 + seconds:
		break
