#!/bin/csh -f

# s_amplify :   amplify all amplitudes by a factor of 1000x
#		avoids problems of amplitude scaling in s_makeavg
#		Usage: s_amplify template
#			Note: will scale amplitude of all *.ner and *.far 
#			files in the local directory
#
#		Wed Oct 25 13:09:40 PDT 2000	awl

source phoelix_params

if ($s_verbose) echo "`basename $0` $argv"
set template=$1
set listfile=$2
### write hlxavg.dek file

set repk =  `head -4 $template | tail -1 | awk '{print $1}'`
set llnum = `grep LL $template | wc -l`

echo "amps X 1000" > hlxavg.dek
echo $llnum "1" $repk $delbr "0" >> hlxavg.dek
echo "0 0 0 0 1" >> hlxavg.dek
echo "1000.0" >> hlxavg.dek

foreach i (`cat $listfile`)
    echo "s_phoelixavg" $i $i
    cp $i $i.orig
    s_phoelixavg $i $i
end
