#!/bin/csh -f
# s_autocont - non interactive version of s_mrccont
# usage:  s_autcocont $stdplot $file.map $axis_change $contour_height $hide_lines $pixelx $pixely $pixelz $title $reverse_sign $num_zsections 
# eg: s_autocont 0 newlist.map 0 5 1 2 2 2  junk 0 1

# Read in the parameters from file
source phoelix_params

if (-f psmrccont.zzz) rm -f psmrccont.zzz
if (-f plot.out) rm -f plot.out

if ($s_verbose) echo `basename $0` $argv

set stdplot = $1
set denfile = $2
set axis_change = $3
set contour_height = $4
set hide_lines = $5
set pixx = $6 
set pixy = $7
set pixz = $8
set title = $9
set reverse_sign = $10
set num_zsections = $11
set plot_size = 8
set circle_radius = 0

if ($stdplot == 0 && $axis_change == 1) then
echo $denfile >> psmrccont.zzz
echo $denfile.rot >> psmrccont.zzz
rm -f $denfile.rot
mmc < psmrccont.zzz > /dev/null
set denfile=$denfile.rot
rm psmrccont.zzz
endif

if ($stdplot == 0) then
echo $stdplot >> psmrccont.zzz
echo $contour_height >> psmrccont.zzz
echo $hide_lines >> psmrccont.zzz
echo $denfile >> psmrccont.zzz
echo $pixx $pixy $pixz >> psmrccont.zzz
echo $title >> psmrccont.zzz
echo $reverse_sign >> psmrccont.zzz
echo $num_zsections >> psmrccont.zzz
echo $plot_size >> psmrccont.zzz
echo $circle_radius >> psmrccont.zzz
endif


if ($stdplot == 1) then
echo $stdplot >> psmrccont.zzz
echo $denfile >> psmrccont.zzz
echo $pixx $pixy $pixz >> psmrccont.zzz
echo $title >> psmrccont.zzz
echo $reverse_sign >> psmrccont.zzz
echo 1 >> psmrccont.zzz
echo $num_zsections >> psmrccont.zzz
echo $plot_size >> psmrccont.zzz
echo $circle_radius >> psmrccont.zzz
endif

psmrccont < psmrccont.zzz > /dev/null
sed 's/^ //' < plot.out > plot.asa
mv plot.asa plot.out
#rm psmrccont.zzz
