#!/bin/csh -f

#####
#
# s_bg: background subtraction and adjust to zero mean
# Usage: s_bg file rowpad 
# Input File: .s / .i / .j
# Output file :
# Created / Removed by script:	.r1
#			       	.rn
#				.subbg
#				.tmp
#
#####

source phoelix_params

if ($s_verbose) echo `basename $0` $argv

set file = $1
set rowpad = $2


# extract the prefix of the file
set filep = $file:r

if ( $rowpad != "" ) then
        pad -r $rowpad -p a < $file > $filep.tmp
else
	mv $file $filep.tmp
endif

# get the row size so that can excise last row
set frow = `hdim -r < $filep.tmp`

# excise row 1 and row n 
excise -r 1 < $filep.tmp > $filep.r1
excise -r $frow < $filep.tmp > $filep.rn

# now do the subtraction
subbg -r1 $filep.r1 -rn $filep.rn < $filep.tmp > $filep.subbg

# get the standard deviation 
set stdev = `avsd -s < $filep.subbg`

# bring to 0 mean with current standard deviation 
stdavsd -m 0.0 -s $stdev < $filep.subbg > $file 

# and cleanup
#rm $filep.r1
#rm $filep.rn
#rm $filep.subbg
#rm $filep.tmp
