#!/bin/csh -f

#####
#
# s_bg: background subtraction and adjust to zero mean
# Usage: s_bg file rowpad 
# Input File: .s / .i / .j
# Output file :
# Created / Removed by script:	.r1
#			       	.rn
#				.subbg
#				.tmp
#
#####

source phoelix_params

if ($s_verbose) echo `basename $0` $argv

set file = $1
set rowpad = $2


# extract the prefix of the file
set filep = $file:r

if ( $rowpad != "" ) then
        pad -r $rowpad -p a < $file > $filep.tmp
else
	mv $file $filep.tmp
endif

# get the row size so that can excise last row
set frow = `hdim -r < $filep.tmrc`
set frow2 = `ee $frow -10`

# excise and collapse first 10 and last 10 rows from the pre-rotated mrc file
excise -r 1-10 < $filep.tmrc > $filep.r1
collapse -c <$filep.r1> $filep.cr1
excise -r $frow2-$frow < $filep.tmrc > $filep.rn
collapse -c <$filep.rn> $filep.crn

# now do the subtraction
subbg -r1 $filep.cr1 -rn $filep.crn < $filep.tmp > $filep.subbg

cp $filep.subbg $file

# get the standard deviation 
#set stdev = `avsd -s < $filep.subbg`

# bring to 0 mean with current standard deviation 
#stdavsd -m 0.0 -s $stdev < $filep.subbg > $file 

# and cleanup
rm $filep.r1 $filep.cr1 $filep.rn $filep.crn $filep.tmp $filep.subbg
