#!/bin/csh -f
#
# s_convert: semi-automated scripts that converts a TIFF micrograph into an MRC and uses EMAN's boxer to box out filaments and assess their diffraction
#
# Input: .tif
# Output: .mrc
# Usage: s_convert infile
# Where:
#	 infile = raw micrograph in tiff format

source master_params
source phoelix_params

set filex = $1
set filep = `prefix $filex`

## Convert TIFF to MRC using EM2EM
echo "*Convert TIFF to MRC by entering the following commands as prompted"
echo "*Please specify option: TIFF"
echo "*Please specify option: MRC"
echo "*Input = set of 2D sections of a 3D volume: NO"
echo "*Import a SET of input image files: NO"
echo "*Input image file: $filex"
echo "*Output image file (WITH EXT.): $filep.mrc"
em2em

## Generate fast fourier transform for future use in CTF estimation (CTFPro)
itp -f 0.5 <$filep.mrc> $filep"bin".mrc
set rows = `hdim -r < $filep"bin".mrc`
set pad2 = `po2 -f $rows`
pad -n $pad2 -p a <$filep"bin".mrc> $filep"bin".pad
tomrc <$filep"bin".pad> $filep"binpad".mrc
s_fftrans $filep"binpad".mrc

## Filter the raw micrograph so filaments can be more easily seen
echo "*Box out your filaments and prepare them for HIP by following the commands as prompted"
echo "*Filter the raw micrograph"
echo "*center click -> Sca: 0.1"
echo "*Process -> Median Filter (9x9)"
echo "*File -> Save Micrograph -> $filep"filt".mrc -> Save"
echo "*Close Boxer"
boxer $filex

## Use Helixboxer to box out good filaments and save the coordinates
echo "*Box out the good filaments"
echo "*center click -> Sca: 0.1"
echo "*Width: $yht -> select filaments"
echo "*File -> Save DB -> $filep"filt".box -> Save"
echo "*Close Helixboxer"
helixboxer $filep"filt".mrc

## Load the filament coordinates onto the raw micrograph and save the boxed out filaments
echo "*center click -> Sca: 0.1"
echo "*File -> Read DB -> select $filep"filt".box"
echo "*File -> Save Particles -> $filep.img -> Save"
echo "*Close Helixboxer"
helixboxer $filex

## Convert the filaments to MRCs and test the diffraction 
ls -1 $filep.*.img > img.list
set lines = `wc -l img.list | awk '{print $1}'`
set i = 1
while ($i <= $lines)
	
	set filen = `head -$i img.list | tail -1`
	set filenp = `prefix $filen`
	
	if ($i <= 9) then
		proc2d $filen $filenp"_0"$i.mrc mrc
		transpose <$filenp"_0"$i.mrc> $filep"_0"$i.tmrc
		mv $filep"_0"$i.tmrc $filenp"_0"$i.mrc
		s_filter $filep"_0"$i.mrc $filep"_0"$i.but 100 $step
		echo "*Cut out a small piece to test diffraction"
		echo "*Use filtered image as reference"
		set tenrep = `ee int[[$xover : $step] x 10]`
		echo "*Mode -> Box Selection -> ($tenrep x $yht) -> Save Boxed Images -> Save -> Close"
		tkir -f $filep"_0"$i.mrc $filep"_0"$i.but
		mv box01.f $filep"_0"$i"_10r".mrc
		set cols = `hdim -c < $filep"_0"$i"_10r".mrc`
		set padc = `po2 -f $cols`
		pad -n $padc -p a < $filep"_0"$i"_10r".mrc | dft > $filep"_0"$i"_10r".dft
		tkir -f $filep"_0"$i"_10r".dft
	else
		proc2d $filen $filenp"_"$i.mrc mrc
		transpose <$filenp"_"$i.mrc> $filep"_"$i.tmrc
		mv $filep"_"$i.tmrc $filenp"_"$i.mrc
		s_filter $filep"_"$i.mrc $filep"_"$i.but 100 $step
		echo "*Cut out a small piece to test diffraction"
		echo "*Use filtered image as reference"
		set tenrep = `ee int[[$xover : $step] x 10]`
		echo "*Mode -> Box Selection -> ($tenrep x $yht) -> Save Boxed Images -> Save -> Close"
		tkir -f $filep"_"$i.mrc $filep"_"$i.but
		mv box01.f $filep"_"$i"_10r".mrc
		set cols = `hdim -c < $filep"_"$i"_10r".mrc`
		set padc = `po2 -f $cols`
		pad -n $padc -p a < $filep"_"$i"_10r".mrc | dft > $filep"_"$i"_10r".dft
		tkir -f $filep"_"$i"_10r".dft
	endif
set i=`ee $i+1`
end
