#!/bin/csh -f
#
# Input: .mrc
# Output: .s 
#
# Usage: s_hip listfile ctflist
#
# listfile is a list of all boxed out, horizontal filaments from the dataset. Preferred filename is micrograph_filament#.  
# A letter must precede the micrograph name if it is a number.  
# ex: if micrograph 4397 has 3 filaments they would be named a4397_01.mrc, a4397_02.mrc, and a4397_03.mrc
#
# ctflist is a list of the micrograph filename prefix and its corresponding defocus value which gets read into s_datacor.
# ex: 	a4397  0.8619
#	a4400  0.8854
#	a4403  0.7876
#	a4406  0.7958
#
# Make sure that master_params and phoelix_params have been modified for your dataset.  
# Things to check are step, ctf, batch, xlngth, yht, padval, yht2, and frowsize.
#
# Also make sure you have llbo.sa, range.sa, strong.sa, template, cutfit1.dek, cutfit2.dek, cutfit3.dek, chop1.dek, and chop2.dek files.
# Template must have the same number of layer lines and same bessel orders as in llbo.sa. Use your best average or near/far file thus far. 
# cutfit.dek files are for averaging. Select optimal layer lines for aligning.  In each file select a few more LLs. 
# ex: cutfit1.dek=LL 5,6,11  cutfit2.dek=LL 5,6,10,11,17  cutfit3.dek=LL 1,5,6,10,11,17,28
# chop.dek files are for sniffing.  chop1.dek should have broader ranges than chop2.dek. Select a range over the meaningful portions on every LL except LL0. 
#
# LSF 11/5/09

source master_params
source phoelix_params

set infile = $1
#set ctflist = $2

## Cut the filaments into small segments 
s_scissors2 $infile $xlngth $yht $ovrlp

## Correct in-plane tilt 
ls -1 *_*_*.mrc > rot.list
s_testrot rot.list $padval

## Correct the ctf with the defocus values estimated in CTFPro 
#ls -1 *_*_*.dft > fulldft.list

#set lines = `wc -l $ctflist | awk '{print $1}'`
#set i = 1
#while ($i <= $lines)
#set filep = `head -$i $ctflist | tail -1 | awk '{print $1}'`
#set defocus = `head -$i $ctflist | tail -1 | awk '{print $2}'`

#grep $filep fulldft.list > $filep"ctf".list
#s_datacor $filep"ctf".list $defocus

#set i = `ee $i + 1`
#end

## Recenter and box out the filament segments 
ls -1 *_*_*.rot > box.list
s_autobox box.list $xlngth $yht2

## Correct tilt and shift using phoelix programs and create near and far files
ls -1 *_*_*.s > maxi.list
s_maxinotilt maxi.list
rm old*

## Average the near and far files 
# Do three round of averaging and two rounds of sniffing. 
mkdir avgsnif1
cp *.ner *.far *params cutfit* chop* template avgsnif1
cd avgsnif1

## Round 1 of Averaging 
# First three steps can be commented out if you already have your cutfit.dek files. 
#tkll -f template -d cutfit1.dek -cut
#tkll -f template -d cutfit2.dek -cut
#tkll -f template -d cutfit3.dek -cut
ls -1 *.ner *.far > avg.list
set filno = `wc -l avg.list | awk '{print $1}'`
echo "Round 1: $filno filaments in avg.list" 
s_fautoavg avg.list 3 avg1 template
cp template avglist3p.avg
cp template template.orig

# Generate overplots and map
# Comment out lines with undesired residual cutoffs 
#s_fpost avg.list 3 40 postavg40 map overplot
#s_fpost avg.list 3 35 postavg35 map overplot
s_fpost avg.list 3 30 postavg30 map overplot
s_fpost avg.list 3 25 postavg25 map overplot
s_fpost avg.list 3 20 postavg20 map overplot
#s_fpost avg.list 3 15 postavg15 map overplot

cp avglist3_30p.avg template

# Prepare directory for Sniffing (s_presnif).  First step can be commented out if you already have chop1.dek.
#tkll -f template -d chop1.dek -cut
s_llcut template snif_template.cut chop1.dek
cp ../*.fft .
cp ../*hlxdump* .
cp ../*hlxavg_dek .
ls -1 *.fft > snif.list
set filno = `wc -l snif.list | awk '{print $1}'`
echo "Round 1: $filno filaments in snif.list" 

## Round 1 of Sniffing
# You should view the snif_template first, but for automation purposes it may be commented out.
#tkll -f snif_template.cut
s_sniffer snif.list
mkdir avgsnif2
cp *_snif.ner *_snif.far *params* cutfit* chop* avgsnif2
cp avglist3_30p.avg avgsnif2/template
cd avgsnif2
ls -1 *.ner *.far > avg.list

## Round 2 of Averaging
set filno = `wc -l avg.list | awk '{print $1}'`
echo "Round 2: $filno filaments in avg.list" 
s_fautoavg avg.list 3 avg2 template
cp template avglist3p.avg

# Generate overplots and map
# Comment out lines with undesired residual cutoffs 
#s_fpost avg.list 3 40 postavg40 map overplot
#s_fpost avg.list 3 35 postavg35 map overplot
s_fpost avg.list 3 30 postavg30 map overplot
s_fpost avg.list 3 25 postavg25 map overplot
s_fpost avg.list 3 20 postavg20 map overplot
#s_fpost avg.list 3 15 postavg15 map overplot

cp avglist3_30p.avg template

# Prepare directory for Sniffing (s_presnif).  First step can be commented out if you already have chop2.dek.
#tkll -0 -f avglist3p.avg -d chop2.dek -cut
s_llcut template snif_template.cut chop2.dek
cp ../*.fft .
cp ../*hlxdump* .
cp ../*hlxavg_dek .
ls -1 *.fft > snif.list
set filno = `wc -l snif.list | awk '{print $1}'`
echo "Round 2: $filno filaments in snif.list" 

## Round 2 of Sniffing
# You should view the snif_template first, but for automation purposes it may be commented out.
#tkll -f snif_template.cut
s_sniffer snif.list
mkdir avg3
cp *_snif.ner *_snif.far *params* cutfit* chop* avg3
cp avglist3_30p.avg avg3/template
cd avg3
ls -1 *.ner *.far > avg.list

## Round 3 of Averaging
set filno = `wc -l avg.list | awk '{print $1}'`
echo "Round 3: $filno filaments in avg.list" 
s_fautoavg avg.list 3 avg3 template

# Generate overplots and map
# Comment out lines with undesired residual cutoffs 
#s_fpost avg.list 3 40 postavg40 map overplot
#s_fpost avg.list 3 35 postavg35 map overplot
s_fpost avg.list 3 30 postavg30 map overplot
s_fpost avg.list 3 25 postavg25 map overplot
s_fpost avg.list 3 20 postavg20 map overplot
#s_fpost avg.list 3 15 postavg15 map overplot

echo "Processing Complete"
exit
