#!/bin/csh -f
#
# s_move: used in s_finddell and s_maxi2 to move all files with the same prefix to a rejects directory.
# 	  this is a little clunky, but necessary because you cannot use a filep* statement inside a loop and we
#         want to remove all files from the working directory so processing is stopped on the bad filaments
#	  and the programs can move on to the next filament without halting automation.
#
# Usage: s_move filename
#
# LSF 10/23/09

set filex = $1
set filep = $filex:r
mkdir -p rejects

mv $filep.* rejects
