#!/bin/csh -f
#source hlx_params
source phoelix_params
if ($s_verbose) echo `basename $0` $argv

set infile=$1
set inches = "2"

unsetenv PSOVERPLOT_OUTPUT_TYPE
if ($#argv == 2) then
	if ("$argv[2]" == "-old") setenv PSOVERPLOT_OUTPUT_TYPE old
	if ("$argv[2]" == "-op") set inches = "0.84"
endif

rm -f overplot.tmp plot.int overplot.in
touch overplot.tmp
touch overplot.in

set firstfile=`head -1 $infile | awk '{print $1}'`
#grep $firstfile $infile >> overplot.tmp
set numlls =  `grep $firstfile $infile | wc -l`
grep "1.000 " $infile > all.tmp
head -$numlls all.tmp >> overplot.tmp

set i=1
set len=`wc -l overplot.tmp | awk '{print $1}'`

echo $infile >> overplot.in
echo "p" >> overplot.in
echo "100" >> overplot.in
echo "20000" >> overplot.in
echo $inches >> overplot.in
echo $delbr >> overplot.in
echo "0.05" >> overplot.in
#echo "l" >> overplot.in
echo "b" >> overplot.in

while ( $i <= $len )
	set ll=`head -$i overplot.tmp | tail -1 | awk '{print $3}'`
	set bo=`head -$i overplot.tmp | tail -1 | awk '{print $2}'`
	set i=`ee $i + 1`
	echo $ll $bo >> overplot.in
end              
echo "-99 -99" >> overplot.in
psoverplot < overplot.in > /dev/null
sed 's/^0//;s/^ //' plot.int > plot.asa
mv plot.asa plot.int
rm all.tmp
#rm overplot.tmp overplot.in
