#!/bin/csh -f

# s_phoelixavg 	Script to run phoelixavg, a version of hlxavg that has been
#		modified by MW and BC for their own nefarious purposes.
#		

source phoelix_params
if ($s_verbose) echo `basename $0` $argv

set filein = $1
set fileout = $2

rm -f fort.2
rm -f fort.3
ln $filein fort.3
ln hlxavg.dek fort.2

phoelixavg

mv fort.1 $fileout
rm fort.7
rm -f fort.2
rm -f fort.3
