#!/bin/csh -f
#
# s_scissors2: cuts filaments into small segments of a specified size, differs from s_scissors in that the segments are not adjacent but rather overlapping by 60%
#
# Input: .mrc
# Output: .mrc
# Usage: s_scissors infile xlngth yht
# Where:
#	infile = list of full length filaments (.mrc) to be segmented
# 	xlngth = length you want your boxed out filaments to be, usually a certain number of helical repeats (ex. 322 pixels)
# 	yht = y value for the final boxed out image (ex. 256 pixels)
# 	in other words, (xlngth,yht) = (x,y) for final boxed out image 
#
# LSF 10/12/09

source phoelix_params

set listfile = $1
set xlngth = $2
set yht = $3
set ovrlp = $4
set lines = `wc -l $listfile | awk '{print $1}'`

set i = 1
while ($i <= $lines)
        set filex = `head -$i $listfile | tail -1`
        set filep = `prefix $filex`
	set ext = `suffix $filex`
	set nrows = `hdim -c < $filex`
	set ovrlpdiff = `ee [100 - $ovrlp]:100`
	set ovrlap = `ee $xlngth x $ovrlpdiff`
	cp $filex $filep"-scsr".$ext

	set j = 1
	while ($nrows >= $xlngth)
		if ($j < 10) then
			pad -x $xlngth -rgt -y $yht < $filep"-scsr".$ext > $filep"_0$j".$ext
		else 
			pad -x $xlngth -rgt -y $yht < $filep"-scsr".$ext > $filep"_$j".$ext
		endif

		set rest = `ee $nrows - $ovrlap`
		pad -x $rest -lft < $filex > $filep"-scsr".$ext
		set nrows = `hdim -c < $filep"-scsr".$ext`
	@ j++
	end
	rm $filep"-scsr".$ext
	set filno = `ls -1 $filep"_"*.$ext | wc -l | awk '{print $1}'`
	echo "$filex cut into $filno pieces"
@ i++
end


