#!/bin/csh -f


set infile = $1
set lines = `wc -l $infile | awk '{print $1}'`
set i = 1

while ($i <= $lines)

	set filex = `head -$i $infile | tail -1`
	set filep = `prefix $filex`
	transpose < $filex > $filep.t
	tomrc <$filep.t> $filep.tmrc
	rm $filep.t

	@ i++
	
end
