#!/usr/bin/perl -w
#
# ASCII-encoding stash program to store register and value in an "info" file.
# Requirements for a tagline containing an integer have been removed.  Also
# filenames with multiple extensions (e.g. image.test.001.f) are now perfectly
# acceptable.
#
# USAGE: stash {info_file_name} {image_id} ={n} {arg}
#
#              {info_file_name}: Name of registry file.  No restriction on name.
#              {image_id}:       Unique filename to allow multiple data entries
#                                (i.e. filenames) to share a common registry
#                                file.
#              {n}:              Register number
#              {arg}:            Value to save.  Can be int or float;
#

if ($#ARGV < 0) {
   die << "USAGE";
USAGE: stash {info_file_name} {image_id} ={n} {arg}

             {info_file_name}: Name of registry file.  No restriction on name.
             {image_id}:       Unique filename to allow multiple data entries
                               (i.e. filenames) to share a common registry
                               file.
             {n}:              Register number
             {arg}:            Value to save.  Can be int or float;
USAGE
}

$infofile = $ARGV[0];
$tagline  = $ARGV[1];
$infoexists = 1;
shift @ARGV;
shift @ARGV;

open(INFO,"<$infofile") || undef $infoexists;
if ($infoexists) {
   while (<INFO>) {
      chomp;
      @entry = split(' ',$_);
      $tag = $entry[0];
      $reg = $entry[1];
      $val = $entry[2];
      $info{"$tag $reg"} = $val;
   }
   close INFO;
}

open(INFO,">$infofile") || die "Can't create $infofile\n";

while ($#ARGV > -1) {
   $reg = $ARGV[0];
   $val = $ARGV[1];
   shift @ARGV;
   shift @ARGV;
   $info{"$tagline $reg"} = $val;
}

foreach $key (keys %info) {
   if (defined $info{$key}) {
      print INFO "$key $info{$key}\n";
   }
}

close INFO;
