#!/bin/csh -f
#
# Basic wrapper for Tkll.  Because tkll can be invoked in "batch" mode
# we need to be able to parse it's calling arguments and if the
# "-batch" flag is detected, invoke the script with the Tcl interpreter "tclsh".
# If the flag is not detected, then we need to run with the GUI enabled, which
# requires invoking the script with the Tcl/Tk interpreter "wish".
#

# By default, we assume tkll is *NOT* run in batch mode
set batchflag = 0

# Parse the command-line arguments, and record if the "-batch" flag is
# found:
foreach arg ($argv)
   if ("$arg" == "-batch" || "$arg" == "-v" || "$arg" == "-vv") then
      set batchflag = 1
   endif
end

# If the batch flag is set, run tkll with the tclsh interpreter, otherwise
# use wish and pull up the GUI.  The script is passed all the command-line
# flags, including the "-batch" if it's present.  This is because the script
# has to know whether to set up the GUI, initialize fonts, etc.
#
# wish and tclsh MUST be in your path for this to fly
if ($batchflag) then
   exec tclsh $SUPRIM_TK_LIB/tkll.tcl $argv -batch
else
   exec wish $SUPRIM_TK_LIB/tkll.tcl -- $argv
endif
