#
# Makefile [make]
#
# Copyright © 2012 Hanspeter Winkler
#


#
# definitions
#

include ../Makedefs

CFLAGS  = $(COPT)
CPPFLAGS = $(CPPOPT)

LDFLAGS = $(LDOPT) $(LDLIBOPT)


#
# make rules
#

.PHONY: help all install clean distclean depend

help:
	@ echo "usage: make [ all | install | depend | clean | distclean ]"

all:

install:

depend:

clean:

distclean:
