#undef any2eucjp
#undef createwbmp
#undef empty_output_buffer
#undef fill_input_buffer
#undef freewbmp
#undef gdAlphaBlend
#undef gdCompareInt
#undef gdCosT
#undef gdCtxPrintf
#undef gdDPExtractData
#undef gdFontGetGiant
#undef gdFontGetLarge
#undef gdFontGetMediumBold
#undef gdFontGetSmall
#undef gdFontGetTiny
#undef gdFontGiant
#undef gdFontGiantData
#undef gdFontGiantRep
#undef gdFontLarge
#undef gdFontLargeData
#undef gdFontLargeRep
#undef gdFontMediumBold
#undef gdFontMediumBoldData
#undef gdFontMediumBoldRep
#undef gdFontSmall
#undef gdFontSmallData
#undef gdFontSmallRep
#undef gdFontTiny
#undef gdFontTinyData
#undef gdFontTinyRep
#undef gdGetBuf
#undef gdGetByte
#undef gdGetC
#undef _gdGetColors
#undef gd_getin
#undef gdGetInt
#undef gdGetWord
#undef gdImageAABlend
#undef gdImageAALine
#undef gdImageAlphaBlending
#undef gdImageAntialias
#undef gdImageArc
#undef gdImageBrightness
#undef gdImageChar
#undef gdImageCharUp
#undef gdImageColor
#undef gdImageColorAllocate
#undef gdImageColorAllocateAlpha
#undef gdImageColorClosest
#undef gdImageColorClosestAlpha
#undef gdImageColorClosestHWB
#undef gdImageColorDeallocate
#undef gdImageColorExact
#undef gdImageColorExactAlpha
#undef gdImageColorMatch
#undef gdImageColorResolve
#undef gdImageColorResolveAlpha
#undef gdImageColorTransparent
#undef gdImageCompare
#undef gdImageContrast
#undef gdImageConvolution
#undef gdImageCopy
#undef gdImageCopyMerge
#undef gdImageCopyMergeGray
#undef gdImageCopyResampled
#undef gdImageCopyResized
#undef gdImageCreate
#undef gdImageCreateFromGd
#undef gdImageCreateFromGd2
#undef gdImageCreateFromGd2Ctx
#undef gdImageCreateFromGd2Part
#undef gdImageCreateFromGd2PartCtx
#undef gdImageCreateFromGd2PartPtr
#undef gdImageCreateFromGd2Ptr
#undef gdImageCreateFromGdCtx
#undef gdImageCreateFromGdPtr
#undef gdImageCreateFromGif
#undef gdImageCreateFromGifCtx
#undef gdImageCreateFromGifSource
#undef gdImageCreateFromJpeg
#undef gdImageCreateFromJpegCtx
#undef gdImageCreateFromJpegPtr
#undef gdImageCreateFromPng
#undef gdImageCreateFromPngCtx
#undef gdImageCreateFromPngPtr
#undef gdImageCreateFromPngSource
#undef gdImageCreateFromWBMP
#undef gdImageCreateFromWBMPCtx
#undef gdImageCreateFromWBMPPtr
#undef gdImageCreateFromXbm
#undef gdImageCreatePaletteFromTrueColor
#undef gdImageCreateTrueColor
#undef gdImageDashedLine
#undef gdImageDestroy
#undef gdImageEdgeDetectQuick
#undef gdImageEllipse
#undef gdImageEmboss
#undef gdImageFill
#undef gdImageFilledArc
#undef gdImageFilledEllipse
#undef gdImageFilledPolygon
#undef gdImageFilledRectangle
#undef _gdImageFillTiled
#undef gdImageFillToBorder
#undef gdImageGaussianBlur
#undef gdImageGd
#undef gdImageGd2
#undef gdImageGd2Ptr
#undef gdImageGdPtr
#undef gdImageGetClip
#undef gdImageGetPixel
#undef gdImageGetTrueColorPixel
#undef gdImageGif
#undef gdImageGifCtx
#undef gdImageGifPtr
#undef gdImageGrayScale
#undef gdImageInterlace
#undef gdImageJpeg
#undef gdImageJpegCtx
#undef gdImageJpegPtr
#undef gdImageLine
#undef gdImageMeanRemoval
#undef gdImageNegate
#undef gdImagePaletteCopy
#undef gdImagePng
#undef gdImagePngCtx
#undef gdImagePngCtxEx
#undef gdImagePngEx
#undef gdImagePngPtr
#undef gdImagePngPtrEx
#undef gdImagePngToSink
#undef gdImagePolygon
#undef gdImageRectangle
#undef gdImageRotate
#undef gdImageRotate180
#undef gdImageRotate270
#undef gdImageRotate45
#undef gdImageRotate90
#undef gdImageSaveAlpha
#undef gdImageSelectiveBlur
#undef gdImageSetAntiAliased
#undef gdImageSetAntiAliasedDontBlend
#undef gdImageSetBrush
#undef gdImageSetClip
#undef gdImageSetPixel
#undef gdImageSetStyle
#undef gdImageSetThickness
#undef gdImageSetTile
#undef gdImageSkewX
#undef gdImageSkewY
#undef gdImageSmooth
#undef gdImageString
#undef gdImageString16
#undef gdImageStringFT
#undef gdImageStringFTEx
#undef gdImageStringTTF
#undef gdImageStringUp
#undef gdImageStringUp16
#undef gdImageTrueColorToPalette
#undef gdImageWBMP
#undef gdImageWBMPCtx
#undef gdImageWBMPPtr
#undef gdImageXbmCtx
#undef gdNewDynamicCtx
#undef gdNewDynamicCtxEx
#undef gdNewFileCtx
#undef gdNewSSCtx
#undef gdPutBuf
#undef gdPutC
#undef _gdPutColors
#undef gdPutInt
#undef gd_putout
#undef gdPutWord
#undef gdSeek
#undef gdSinT
#undef gd_strtok_r
#undef gdTell
#undef getmbi
#undef init_destination
#undef init_source
#undef jpeg_gdIOCtx_dest
#undef jpeg_gdIOCtx_src
#undef lsqrt
#undef printwbmp
#undef Putchar
#undef putmbi
#undef Putword
#undef readwbmp
#undef skipheader
#undef skip_input_data
#undef term_destination
#undef term_source
#undef writewbmp
#undef ZeroDataBlock
#undef gdCacheCreate
#undef gdCacheDelete
#undef gdCacheGet
#undef gdFontCacheSetup
#undef gdFontCacheShutdown
#undef gdFreeFontCache
