#!/usr/bin/env python

import sys
from pyami import mrc, numpil
from optparse import OptionParser

parser = OptionParser()

parser.add_option('-f', '--format', action='store', dest='format',
                  help="output file format")
(options, args) = parser.parse_args()

format = options.format

infile = args[0]
try:
	outfile = args[1]
except IndexError:
	outfile = None

im = mrc.read(infile)
numpil.write(im, outfile, format=format)
