#!/usr/bin/env python

from optparse import OptionParser
import sys
from pyami import mrc
import numpy

usage = '''
Convert an MRC image file from one mode to another.
   %prog -m mode inputmrc outputmrc

  MODE   data type
  ----   ---------
     0   signed 8-bit bytes range -128 to 127
     1   16-bit halfwords
     2   32-bit reals
     3   complex 16-bit integers
     4   complex 32-bit reals
     6   unsigned 16-bit range 0 to 65535
'''

parser = OptionParser(usage=usage)
parser.add_option('-m', '--mode', action='store', dest='mode',
                  help='MRC mode number')

(options, args) = parser.parse_args()

'''
if options.help:
	import version
	print 'Leginon version: %s' % (version.getVersion(),)
	print '   Installed in: %s' % (version.getInstalledLocation(),)
	sys.exit()
'''

needhelp = False
try:
	mode = int(options.mode)
except:
	needhelp = True

if len(args) != 2:
	needhelp = True

if needhelp:
	parser.print_help()
	sys.exit()

infile = args[0]
outfile = args[1]

input = mrc.read(infile)
newtype = mrc.mrc2numpy[mode]
output = numpy.asarray(input, newtype)
mrc.write(output, outfile)
