#
# Makefile [core/config]
#
# Copyright © 2012 Hanspeter Winkler
#


#
# definitions
#

include ../../Makedefs

PRFX = core

INCS = $(PRFX)config.h config.h modulebase.h defs.h coretypedefs.h macros.h mathdefs.h physdefs.h emdefs.h

OBJS = $(PRFX)config.o coretypedefs.o

CFLAGS = $(CLIBOPT)
CPPFLAGS = $(CPPOPT)


#
# make rules
#

include ../../make/Makeconfig


#
# build dependencies
#

-include Makedeps
