<?php

require "inc/project.inc.php";
require "inc/leginon.inc";
require "inc/confirmlib.php";
require "inc/utilpj.inc.php";
require "inc/aform.php";

$confirmId = ($_GET['id']) ? $_GET['id'] : $_POST['confirmId'];
$projectId = ($_GET['pid']) ? $_GET['pid'] : $_POST['projectId'];

$is_admin = checkProjectAdminPrivilege($projectId);
if ($is_admin) {
	$title = "Projects";
	login_header($title);
} else {
	$redirect=$_SERVER['PHP_SELF'];
	redirect(BASE_URL.'login.php?ln='.$redirect);
}

$confirm = new Confirm();

// --- map db fields and form --- //
	$map=array();
	$map['duedate']="c3";
	$map['deliverables']="c4";
	$map['confirmnum']="c5";
	$map['note']="c6";
	$map['samplerequest']="c7";
	$map['experimentrequest']="c8";
if ($_POST ) {
	$data_from_post=from_POST_values(array_values($map));
print_r($data_from_post);
print_r($_POST);

	foreach($map as $k=>$v) {
		if (ereg("date$", $k)) {
			$$k=mysql::format_date($data_from_post[$v]);
		} else {
			$$k=$data_from_post[$v];
		}
	}

	$confirmnum=ereg_replace("^C","",$confirmnum);
	if ($_POST['btsubmit']=='add') {
		$confirmId = $confirm->addConfirm($projectId, $duedate, $deliverables, $confirmnum, $note, $samplerequest, $experimentrequest);

	} else if ($_POST['btsubmit']=='update') {
		$confirm->updateConfirm($confirmId, $projectId, $duedate, $deliverables, $confirmnum, $note, $samplerequest, $experimentrequest);
	}

// --- redirect after submission --- //
	if ($_POST['btsubmit']=='add' || $_POST['btsubmit']=='update') {
		redirect($_GET['ln']);
	}
} 

if (empty($confirmId) || !($confirm->checkConfirmExistsbyId($confirmId))) {
	$title='- new confirm';
	$action='add';
	$newnumber=$confirm->getNextNumber($projectId);
	$newnumberstr=$confirm->format_number($newnumber);
} else {
	$title='- update confirm: '.$curconfirm['Name'];
	$action='update';

}

$defaults["c5"]=$newnumberstr;

if ($confirmId) {
$curconfirm = $confirm->getConfirmInfo($confirmId);
print_r($curconfirm);
foreach($map as $k=>$v) {
	$val=$curconfirm[$k];
	if (ereg("date$", $k)) {
			$val=mysql::format_date($val, "ymd", "mdy", "-" );
	}
	if ($v=="c5") {
		$val=$confirm->format_number($val);
	}
	$defaults[$v]=$val;
}
}
	

project_header("Confirm $title");
?>

<a href="<?=$_GET['ln'];?>">[ &laquo; back ]</a>
<p>
<font color=red>*</font>
<font face="Arial, Helvetica, sans-serif" size="2">: required fields</font>
</p>
<link href="css/aform.css" rel="stylesheet" type="text/css" />
<?

$form=new form();
$form->setPrefix("c");
$form->action=$_SERVER['REQUEST_URI'];
$form->setDefaults($defaults);
$form->onsubmit="return validate();";

$form->addHiddenField('projectId', $projectId);
$form->addHiddenField('confirmId', $confirmId);
$form->addDate("Project Due Date", 20, true);
$form->addTextArea("Deliverables", 6, 50, false);
$form->addField("confirmation number", 20, false, "Number generated by DB: eg, C001");
$form->addTextArea("note", 6, 50, false);
$form->addTextArea("Sample Request", 6, 50, false);
$form->addTextArea("Experiment Sample Request", 6, 50, false);

$form->addSubmit("btsubmit", $action);

echo $form->display();
echo $form->getFormValidation();
project_footer();
?>
