#
# Makefile [core]
#
# Copyright © 2012 Hanspeter Winkler
#

#
# definitions
#

include   ../Makedefs

LIBMAJOR = 2

LIBMINOR = 1.0

PRFX = gui

DIRS = config graph

EXTRADIRS = 

SOLIBS  =



#
# dependencies
#

graph: config


#
# common rules
#

include ../make/Makecommon
