#!/bin/sh
make clean
rm acinclude.m4
rm aclocal.m4
rm -rf autom4te.cache
rm -rf build
rm config.guess
rm config.h
rm config.h.in
rm config.log
rm config.nice
rm config.status
rm config.sub
rm configure
rm configure.in
rm .deps
rm -rf include
rm install-sh
rm libtool
rm ltmain.sh
rm Makefile
rm Makefile.fragments
rm Makefile.global
rm Makefile.objects
rm missing
rm mkinstalldirs
rm -rf modules
